import type {
  FarmerProfile,
  FarmerContext,
  UrgencyResponse,
  RankResponse,
  ReceptivityResponse,
  CropCalendarResponse,
} from "./api";

// Live-extracted responses from KrishiMitra Microservices (M1, M4, M5, M6, M7, M8, M16)
// for the 5 targeted demonstration farmers across India.

export const CACHED_FARMERS: FarmerProfile[] = [
  {
    grower_id: "GRW_00001",
    name: "Grower GRW_00001",
    grower_age: 42,
    phone: "+91-9000000000",
    preferred_language: "Hindi",
    state: "Uttar Pradesh",
    district: "Kanpur Nagar",
    tehsil: "Kanpur_Nagar_T124",
    grower_farm_size: 1.33,
    crops: ["wheat"],
    latitude: 26.8467,
    longitude: 80.9462,
    device_type: "android",
    connectivity: "4G",
    whatsapp_enabled: true,
    last_message_sent_at: null,
    messages_received_last_30d: 0,
    messages_opened_last_30d: 0,
    preferred_contact_time: "morning",
    linked_retailer_id: "RET-200",
    linked_retailer_name: "Kanpur Nagar Agro Center",
    urgency_score: 0.58,
    recommended_channel: "whatsapp",
  },
  {
    grower_id: "GRW_00005",
    name: "Rajan Kumar",
    grower_age: 38,
    phone: "+91-9000000001",
    preferred_language: "Hindi",
    state: "Uttar Pradesh",
    district: "Lucknow",
    tehsil: "Lucknow_Rural",
    grower_farm_size: 2.1,
    crops: ["wheat"],
    latitude: 26.85,
    longitude: 80.95,
    device_type: "android",
    connectivity: "4G",
    whatsapp_enabled: true,
    last_message_sent_at: null,
    messages_received_last_30d: 0,
    messages_opened_last_30d: 0,
    preferred_contact_time: "morning",
    linked_retailer_id: "RET-201",
    linked_retailer_name: "Lucknow Agro Center",
    urgency_score: 0.58,
    recommended_channel: "whatsapp",
  },
  {
    grower_id: "GJ-014",
    name: "Mayur",
    grower_age: 34,
    phone: "+919152155576",
    preferred_language: "Gujarati",
    state: "Gujarat",
    district: "Anand",
    tehsil: "Borivali",
    grower_farm_size: 1.8,
    crops: ["cotton"],
    latitude: 22.5645,
    longitude: 72.9289,
    device_type: "android",
    connectivity: "4G",
    whatsapp_enabled: true,
    last_message_sent_at: null,
    messages_received_last_30d: 0,
    messages_opened_last_30d: 0,
    preferred_contact_time: "morning",
    linked_retailer_id: "RET-202",
    linked_retailer_name: "Anand Agro Center",
    urgency_score: 0.58,
    recommended_channel: "whatsapp",
  },
  {
    grower_id: "BR-001",
    name: "Rajnish",
    grower_age: 45,
    phone: "+91-9000000003",
    preferred_language: "Bhojpuri",
    state: "Bihar",
    district: "Patna",
    tehsil: "Danapur",
    grower_farm_size: 1.2,
    crops: ["rice"],
    latitude: 25.5941,
    longitude: 85.1376,
    device_type: "feature_phone",
    connectivity: "2G",
    whatsapp_enabled: false,
    last_message_sent_at: null,
    messages_received_last_30d: 0,
    messages_opened_last_30d: 0,
    preferred_contact_time: "morning",
    linked_retailer_id: "RET-203",
    linked_retailer_name: "Patna Agro Center",
    urgency_score: 0.58,
    recommended_channel: "sms",
  },
  {
    grower_id: "TN-042",
    name: "Rajan Kumar",
    grower_age: 50,
    phone: "+91-9000000004",
    preferred_language: "Tamil",
    state: "Tamil Nadu",
    district: "Thanjavur",
    tehsil: "Papanasam",
    grower_farm_size: 2.5,
    crops: ["rice"],
    latitude: 10.787,
    longitude: 79.1378,
    device_type: "android",
    connectivity: "4G",
    whatsapp_enabled: true,
    last_message_sent_at: null,
    messages_received_last_30d: 0,
    messages_opened_last_30d: 0,
    preferred_contact_time: "morning",
    linked_retailer_id: "RET-204",
    linked_retailer_name: "Thanjavur Agro Center",
    urgency_score: 0.82,
    recommended_channel: "voice_call",
  },
];

export const CACHED_CONTEXTS: Record<string, FarmerContext> = {
  GRW_00001: {
    profile: CACHED_FARMERS[0],
    signals: {
      district: "Lucknow",
      state: "Uttar Pradesh",
      humidity_7d_avg: 79.19,
      rainfall_deviation_pct: 402.69,
      weather_anomaly: 1.0,
      pest_risk: 0.2,
      active_pest: "None",
      weather_anomaly_flag: true,
    },
    crop_stage: {
      confirmed_stage: "fallow",
      days_in_stage: 0,
      crop_vulnerability: 0.2,
      days_to_next_stage: 15,
    },
    assembled_at: "2026-09-27T20:57:32.522582",
  },
  GRW_00005: {
    profile: CACHED_FARMERS[1],
    signals: {
      district: "Lucknow",
      state: "Uttar Pradesh",
      humidity_7d_avg: 79.19,
      rainfall_deviation_pct: 402.69,
      weather_anomaly: 1.0,
      pest_risk: 0.2,
      active_pest: "None",
      weather_anomaly_flag: true,
    },
    crop_stage: {
      confirmed_stage: "fallow",
      days_in_stage: 0,
      crop_vulnerability: 0.2,
      days_to_next_stage: 15,
    },
    assembled_at: "2026-09-27T20:56:25.247022",
  },
  "GJ-014": {
    profile: CACHED_FARMERS[2],
    signals: {
      district: "Anand Rural Taluka",
      state: "Gujarat",
      humidity_7d_avg: 67.12,
      rainfall_deviation_pct: -100.0,
      weather_anomaly: 1.0,
      pest_risk: 0.2,
      active_pest: "None",
      weather_anomaly_flag: true,
    },
    crop_stage: {
      confirmed_stage: "flowering",
      days_in_stage: 0,
      crop_vulnerability: 0.8,
      days_to_next_stage: 30,
    },
    assembled_at: "2026-09-27T20:59:18.160981",
  },
  "BR-001": {
    profile: CACHED_FARMERS[3],
    signals: {
      district: "Patna",
      state: "Bihar",
      humidity_7d_avg: 65.0,
      rainfall_deviation_pct: 564.45,
      weather_anomaly: 1.0,
      pest_risk: 0.2,
      active_pest: "None",
      weather_anomaly_flag: true,
    },
    crop_stage: {
      confirmed_stage: "flowering",
      days_in_stage: 0,
      crop_vulnerability: 0.8,
      days_to_next_stage: 30,
    },
    assembled_at: "2026-09-27T21:00:01.379402",
  },
  "TN-042": {
    profile: CACHED_FARMERS[4],
    signals: {
      district: "Thanjavur",
      state: "Tamil Nadu",
      humidity_7d_avg: 73.61,
      rainfall_deviation_pct: 1531.73,
      weather_anomaly: 1.0,
      pest_risk: 0.8,
      active_pest: "Fungal Blast",
      weather_anomaly_flag: true,
    },
    crop_stage: {
      confirmed_stage: "flowering",
      days_in_stage: 0,
      crop_vulnerability: 0.8,
      days_to_next_stage: 30,
    },
    assembled_at: "2026-09-27T21:00:40.336581",
  },
};

export const CACHED_SCORES: Record<string, UrgencyResponse> = {
  GRW_00001: {
    grower_id: "GRW_00001",
    urgency_score: 0.58,
    urgency_components: {
      pest_risk_term: 0.08,
      weather_anomaly_term: 0.3,
      crop_vulnerability_term: 0.1,
      recency_term: 0.1,
      recency_penalty_raw: 0.0,
      weights_source: "default",
      weights_used: {
        pest_risk: 0.4,
        weather_anomaly: 0.3,
        crop_vulnerability: 0.2,
        communication_window: 0.1,
      },
      top_factors: [
        "Severe Weather Deviation",
        "Critical Crop Stage Vulnerability",
        "Communication Window Available",
      ],
    },
    engagement_score: 0.3,
    engagement_components: {
      calibrated_probability: null,
      engagement_scaled: 0.3,
      top_factors: ["Baseline engagement estimate"],
      model_used: false,
    },
    intervention_priority: 0.55,
    recommended_channel: "whatsapp",
    suppress: false,
    suppress_reason: null,
    top_factors: [
      "Severe Weather Deviation",
      "Critical Crop Stage Vulnerability",
      "Communication Window Available",
    ],
    confidence: 0.55,
    expected_intervention_value: 0.124,
    model_version: "m7-hybrid-v2",
  },
  GRW_00005: {
    grower_id: "GRW_00005",
    urgency_score: 0.58,
    urgency_components: {
      pest_risk_term: 0.08,
      weather_anomaly_term: 0.3,
      crop_vulnerability_term: 0.1,
      recency_term: 0.1,
      recency_penalty_raw: 0.0,
      weights_source: "default",
      weights_used: {
        pest_risk: 0.4,
        weather_anomaly: 0.3,
        crop_vulnerability: 0.2,
        communication_window: 0.1,
      },
      top_factors: [
        "Severe Weather Deviation",
        "Critical Crop Stage Vulnerability",
        "Communication Window Available",
      ],
    },
    engagement_score: 0.3,
    engagement_components: {
      calibrated_probability: null,
      engagement_scaled: 0.3,
      top_factors: ["Baseline engagement estimate"],
      model_used: false,
    },
    intervention_priority: 0.55,
    recommended_channel: "whatsapp",
    suppress: false,
    suppress_reason: null,
    top_factors: [
      "Severe Weather Deviation",
      "Critical Crop Stage Vulnerability",
      "Communication Window Available",
    ],
    confidence: 0.55,
    expected_intervention_value: 0.124,
    model_version: "m7-hybrid-v2",
  },
  "GJ-014": {
    grower_id: "GJ-014",
    urgency_score: 0.58,
    urgency_components: {
      pest_risk_term: 0.08,
      weather_anomaly_term: 0.3,
      crop_vulnerability_term: 0.1,
      recency_term: 0.1,
      recency_penalty_raw: 0.0,
      weights_source: "default",
      weights_used: {
        pest_risk: 0.4,
        weather_anomaly: 0.3,
        crop_vulnerability: 0.2,
        communication_window: 0.1,
      },
      top_factors: [
        "Severe Weather Deviation",
        "Critical Crop Stage Vulnerability",
        "Communication Window Available",
      ],
    },
    engagement_score: 0.3,
    engagement_components: {
      calibrated_probability: null,
      engagement_scaled: 0.3,
      top_factors: ["Baseline engagement estimate"],
      model_used: false,
    },
    intervention_priority: 0.55,
    recommended_channel: "whatsapp",
    suppress: false,
    suppress_reason: null,
    top_factors: [
      "Severe Weather Deviation",
      "Critical Crop Stage Vulnerability",
      "Communication Window Available",
    ],
    confidence: 0.55,
    expected_intervention_value: 0.124,
    model_version: "m7-hybrid-v2",
  },
  "BR-001": {
    grower_id: "BR-001",
    urgency_score: 0.58,
    urgency_components: {
      pest_risk_term: 0.08,
      weather_anomaly_term: 0.3,
      crop_vulnerability_term: 0.1,
      recency_term: 0.1,
      recency_penalty_raw: 0.0,
      weights_source: "default",
      weights_used: {
        pest_risk: 0.4,
        weather_anomaly: 0.3,
        crop_vulnerability: 0.2,
        communication_window: 0.1,
      },
      top_factors: [
        "Severe Weather Deviation",
        "Critical Crop Stage Vulnerability",
        "Communication Window Available",
      ],
    },
    engagement_score: 0.3,
    engagement_components: {
      calibrated_probability: null,
      engagement_scaled: 0.3,
      top_factors: ["Baseline engagement estimate"],
      model_used: false,
    },
    intervention_priority: 0.55,
    recommended_channel: "sms",
    suppress: false,
    suppress_reason: null,
    top_factors: [
      "Severe Weather Deviation",
      "Critical Crop Stage Vulnerability",
      "Communication Window Available",
    ],
    confidence: 0.55,
    expected_intervention_value: 0.124,
    model_version: "m7-hybrid-v2",
  },
  "TN-042": {
    grower_id: "TN-042",
    urgency_score: 0.82,
    urgency_components: {
      pest_risk_term: 0.32,
      weather_anomaly_term: 0.3,
      crop_vulnerability_term: 0.1,
      recency_term: 0.1,
      recency_penalty_raw: 0.0,
      weights_source: "default",
      weights_used: {
        pest_risk: 0.4,
        weather_anomaly: 0.3,
        crop_vulnerability: 0.2,
        communication_window: 0.1,
      },
      top_factors: [
        "High Pest Outbreak Risk",
        "Severe Weather Deviation",
        "Critical Crop Stage Vulnerability",
      ],
    },
    engagement_score: 0.3,
    engagement_components: {
      calibrated_probability: null,
      engagement_scaled: 0.3,
      top_factors: ["Baseline engagement estimate"],
      model_used: false,
    },
    intervention_priority: 0.77,
    recommended_channel: "voice_call",
    suppress: false,
    suppress_reason: null,
    top_factors: [
      "High Pest Outbreak Risk",
      "Severe Weather Deviation",
      "Critical Crop Stage Vulnerability",
    ],
    confidence: 0.55,
    expected_intervention_value: 0.196,
    model_version: "m7-hybrid-v2",
  },
};

export const CACHED_PRODUCTS: Record<string, RankResponse> = {
  GRW_00001: {
    grower_id: "GRW_00001",
    crop: "wheat",
    pest: "rust",
    top_products: [
      {
        product_name: "Tilt 250 EC",
        match_score: 0.754,
        confidence: 0.7,
        match_reasons: [
          "Registered for wheat crop protection",
          "Effective at general growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.922,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-3",
          treatment_intent: ["preventive", "curative"],
          price_tier: "low",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
      {
        product_name: "Amistar 250 SC",
        match_score: 0.71,
        confidence: 0.7,
        match_reasons: [
          "Registered for wheat crop protection",
          "Targets rust — efficacy rating 91%",
          "Effective at general growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.932,
          adoption: 0.5,
          availability: 0.47,
          moa_group: "FRAC-11",
          treatment_intent: ["preventive", "curative"],
          price_tier: "premium",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
      {
        product_name: "Kavach 75 WP",
        match_score: 0.626,
        confidence: 0.63,
        match_reasons: [
          "Targets rust — efficacy rating 84%",
          "Effective at general growth stage",
        ],
        score_breakdown: {
          efficacy: 0.668,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-M5",
          treatment_intent: ["preventive"],
          price_tier: "low",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
    ],
    not_recommended: [
      {
        product_name: "Score 250 EC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Alto 5 SC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Cruiser 350 FS",
        not_ranked_higher_because: ["Lower combined score than selected alternatives"],
      },
    ],
    resistance_advisory: null,
    fallback_used: false,
    model_version: "m8-hybrid-v1",
  },
  GRW_00005: {
    grower_id: "GRW_00005",
    crop: "wheat",
    pest: "rust",
    top_products: [
      {
        product_name: "Score 250 EC",
        match_score: 0.75,
        confidence: 0.7,
        match_reasons: [
          "Registered for wheat crop protection",
          "Effective at general growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.93,
          adoption: 0.5,
          availability: 0.62,
          moa_group: "FRAC-3",
          treatment_intent: ["preventive", "curative"],
          price_tier: "mid",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
      {
        product_name: "Amistar 250 SC",
        match_score: 0.734,
        confidence: 0.7,
        match_reasons: [
          "Registered for wheat crop protection",
          "Targets rust — efficacy rating 91%",
          "Effective at general growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.932,
          adoption: 0.5,
          availability: 0.56,
          moa_group: "FRAC-11",
          treatment_intent: ["preventive", "curative"],
          price_tier: "premium",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
      {
        product_name: "Kavach 75 WP",
        match_score: 0.609,
        confidence: 0.63,
        match_reasons: [
          "Targets rust — efficacy rating 84%",
          "Effective at general growth stage",
        ],
        score_breakdown: {
          efficacy: 0.668,
          adoption: 0.5,
          availability: 0.59,
          moa_group: "FRAC-M5",
          treatment_intent: ["preventive"],
          price_tier: "low",
          weights_used: { efficacy: 0.5, adoption: 0.22, availability: 0.27 },
        },
      },
    ],
    not_recommended: [
      {
        product_name: "Alto 5 SC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Tilt 250 EC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Cruiser 350 FS",
        not_ranked_higher_because: ["Lower combined score than selected alternatives"],
      },
    ],
    resistance_advisory: null,
    fallback_used: false,
    model_version: "m8-hybrid-v1",
  },
  "GJ-014": {
    grower_id: "GJ-014",
    crop: "cotton",
    pest: "rust",
    top_products: [
      {
        product_name: "Tilt 250 EC",
        match_score: 0.631,
        confidence: 0.64,
        match_reasons: [
          "Effective at flowering growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.672,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-3",
          treatment_intent: ["preventive", "curative"],
          price_tier: "low",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
      {
        product_name: "Kavach 75 WP",
        match_score: 0.629,
        confidence: 0.63,
        match_reasons: [
          "Targets rust — efficacy rating 84%",
          "Effective at flowering growth stage",
        ],
        score_breakdown: {
          efficacy: 0.668,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-M5",
          treatment_intent: ["preventive"],
          price_tier: "low",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
      {
        product_name: "Amistar 250 SC",
        match_score: 0.588,
        confidence: 0.64,
        match_reasons: [
          "Targets rust — efficacy rating 91%",
          "Effective at flowering growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.682,
          adoption: 0.5,
          availability: 0.47,
          moa_group: "FRAC-11",
          treatment_intent: ["preventive", "curative"],
          price_tier: "premium",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
    ],
    not_recommended: [
      {
        product_name: "Score 250 EC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Alto 5 SC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Cruiser 350 FS",
        not_ranked_higher_because: ["Lower combined score than selected alternatives"],
      },
    ],
    resistance_advisory: null,
    fallback_used: false,
    model_version: "m8-hybrid-v1",
  },
  "BR-001": {
    grower_id: "BR-001",
    crop: "rice",
    pest: "rust",
    top_products: [
      {
        product_name: "Tilt 250 EC",
        match_score: 0.763,
        confidence: 0.7,
        match_reasons: [
          "Registered for rice crop protection",
          "Effective at flowering growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.922,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-3",
          treatment_intent: ["preventive", "curative"],
          price_tier: "low",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
      {
        product_name: "Kavach 75 WP",
        match_score: 0.629,
        confidence: 0.63,
        match_reasons: [
          "Targets rust — efficacy rating 84%",
          "Effective at flowering growth stage",
        ],
        score_breakdown: {
          efficacy: 0.668,
          adoption: 0.5,
          availability: 0.65,
          moa_group: "FRAC-M5",
          treatment_intent: ["preventive"],
          price_tier: "low",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
      {
        product_name: "Amistar 250 SC",
        match_score: 0.588,
        confidence: 0.64,
        match_reasons: [
          "Targets rust — efficacy rating 91%",
          "Effective at flowering growth stage",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.682,
          adoption: 0.5,
          availability: 0.47,
          moa_group: "FRAC-11",
          treatment_intent: ["preventive", "curative"],
          price_tier: "premium",
          weights_used: { efficacy: 0.53, adoption: 0.2, availability: 0.27 },
        },
      },
    ],
    not_recommended: [
      {
        product_name: "Score 250 EC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Alto 5 SC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Vibrance Integral",
        not_ranked_higher_because: ["Premium pricing — may not suit small farm budget"],
      },
    ],
    resistance_advisory: null,
    fallback_used: false,
    model_version: "m8-hybrid-v1",
  },
  "TN-042": {
    grower_id: "TN-042",
    crop: "rice",
    pest: "fungal",
    top_products: [
      {
        product_name: "Tilt 250 EC",
        match_score: 0.795,
        confidence: 0.7,
        match_reasons: [
          "Registered for rice crop protection",
          "Effective at flowering growth stage",
          "Curative action — suitable for high-urgency intervention",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.972,
          adoption: 0.5,
          availability: 0.59,
          moa_group: "FRAC-3",
          treatment_intent: ["preventive", "curative"],
          price_tier: "low",
          weights_used: { efficacy: 0.58, adoption: 0.17, availability: 0.26 },
        },
      },
      {
        product_name: "Amistar 250 SC",
        match_score: 0.649,
        confidence: 0.67,
        match_reasons: [
          "Effective at flowering growth stage",
          "Curative action — suitable for high-urgency intervention",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.732,
          adoption: 0.5,
          availability: 0.56,
          moa_group: "FRAC-11",
          treatment_intent: ["preventive", "curative"],
          price_tier: "premium",
          weights_used: { efficacy: 0.58, adoption: 0.17, availability: 0.26 },
        },
      },
      {
        product_name: "Vibrance Integral",
        match_score: 0.648,
        confidence: 0.67,
        match_reasons: [
          "Registered for rice crop protection",
          "Systemic action — absorbed and translocated in plant",
        ],
        score_breakdown: {
          efficacy: 0.73,
          adoption: 0.5,
          availability: 0.56,
          moa_group: "FRAC-11+7 / IRAC-4A",
          treatment_intent: ["preventive", "seed_treatment"],
          price_tier: "premium",
          weights_used: { efficacy: 0.58, adoption: 0.17, availability: 0.26 },
        },
      },
    ],
    not_recommended: [
      {
        product_name: "Score 250 EC",
        not_ranked_higher_because: ["Same MoA group (FRAC-3) already represented in recommendations"],
      },
      {
        product_name: "Kavach 75 WP",
        not_ranked_higher_because: ["Lower combined score than selected alternatives"],
      },
      {
        product_name: "Alto 5 SC",
        not_ranked_higher_because: ["Lower combined score than selected alternatives"],
      },
    ],
    resistance_advisory: null,
    fallback_used: false,
    model_version: "m8-hybrid-v1",
  },
};

export const CACHED_RECEPTIVITY: Record<string, ReceptivityResponse> = {
  GRW_00001: {
    grower_id: "GRW_00001",
    segment: "offline_only",
    segment_confidence: 0.8,
    receptivity_score: 0.15,
    recommended_formats: [
      {
        format: "field_demo",
        predicted_engagement: 0.22,
        confidence: 0.7,
        reasoning: "In-person demonstration builds trust for new products",
      },
      {
        format: "voice_ivr",
        predicted_engagement: 0.12,
        confidence: 0.7,
        reasoning: "Voice in local language overcomes literacy barriers",
      },
      {
        format: "sms_short",
        predicted_engagement: 0.06,
        confidence: 0.7,
        reasoning: "Reaches keypad users; concise actionable message",
      },
    ],
    best_day_of_week: "Saturday",
    best_time_window: "10:00 AM–12:00 PM",
    fatigue_risk: 0.1,
    creative_suggestions: [
      "Prioritize voice/IVR in local language over digital formats",
      "Coordinate with field rep visit for in-person demonstration",
      "Low fatigue — safe to increase message frequency this week",
      "Low receptivity predicted — consider escalating to field visit or voice call",
    ],
    model_version: "campaign-receptivity-v1",
  },
  GRW_00005: {
    grower_id: "GRW_00005",
    segment: "offline_only",
    segment_confidence: 0.8,
    receptivity_score: 0.15,
    recommended_formats: [
      {
        format: "field_demo",
        predicted_engagement: 0.22,
        confidence: 0.7,
        reasoning: "In-person demonstration builds trust for new products",
      },
      {
        format: "voice_ivr",
        predicted_engagement: 0.12,
        confidence: 0.7,
        reasoning: "Voice in local language overcomes literacy barriers",
      },
      {
        format: "sms_short",
        predicted_engagement: 0.06,
        confidence: 0.7,
        reasoning: "Reaches keypad users; concise actionable message",
      },
    ],
    best_day_of_week: "Saturday",
    best_time_window: "10:00 AM–12:00 PM",
    fatigue_risk: 0.1,
    creative_suggestions: [
      "Prioritize voice/IVR in local language over digital formats",
      "Coordinate with field rep visit for in-person demonstration",
      "Low fatigue — safe to increase message frequency this week",
      "Low receptivity predicted — consider escalating to field visit or voice call",
    ],
    model_version: "campaign-receptivity-v1",
  },
  "GJ-014": {
    grower_id: "GJ-014",
    segment: "offline_only",
    segment_confidence: 0.8,
    receptivity_score: 0.15,
    recommended_formats: [
      {
        format: "field_demo",
        predicted_engagement: 0.22,
        confidence: 0.7,
        reasoning: "In-person demonstration builds trust for new products",
      },
      {
        format: "voice_ivr",
        predicted_engagement: 0.12,
        confidence: 0.7,
        reasoning: "Voice in local language overcomes literacy barriers",
      },
      {
        format: "sms_short",
        predicted_engagement: 0.06,
        confidence: 0.7,
        reasoning: "Reaches keypad users; concise actionable message",
      },
    ],
    best_day_of_week: "Saturday",
    best_time_window: "10:00 AM–12:00 PM",
    fatigue_risk: 0.1,
    creative_suggestions: [
      "Prioritize voice/IVR in local language over digital formats",
      "Coordinate with field rep visit for in-person demonstration",
      "Low fatigue — safe to increase message frequency this week",
      "Low receptivity predicted — consider escalating to field visit or voice call",
    ],
    model_version: "campaign-receptivity-v1",
  },
  "BR-001": {
    grower_id: "BR-001",
    segment: "offline_only",
    segment_confidence: 0.8,
    receptivity_score: 0.15,
    recommended_formats: [
      {
        format: "field_demo",
        predicted_engagement: 0.22,
        confidence: 0.7,
        reasoning: "In-person demonstration builds trust for new products",
      },
      {
        format: "voice_ivr",
        predicted_engagement: 0.12,
        confidence: 0.7,
        reasoning: "Voice in local language overcomes literacy barriers",
      },
      {
        format: "sms_short",
        predicted_engagement: 0.06,
        confidence: 0.7,
        reasoning: "Reaches keypad users; concise actionable message",
      },
    ],
    best_day_of_week: "Saturday",
    best_time_window: "10:00 AM–12:00 PM",
    fatigue_risk: 0.1,
    creative_suggestions: [
      "Prioritize voice/IVR in local language over digital formats",
      "Coordinate with field rep visit for in-person demonstration",
      "Low fatigue — safe to increase message frequency this week",
      "Low receptivity predicted — consider escalating to field visit or voice call",
    ],
    model_version: "campaign-receptivity-v1",
  },
  "TN-042": {
    grower_id: "TN-042",
    segment: "offline_only",
    segment_confidence: 0.8,
    receptivity_score: 0.15,
    recommended_formats: [
      {
        format: "field_demo",
        predicted_engagement: 0.22,
        confidence: 0.7,
        reasoning: "In-person demonstration builds trust for new products",
      },
      {
        format: "voice_ivr",
        predicted_engagement: 0.12,
        confidence: 0.7,
        reasoning: "Voice in local language overcomes literacy barriers",
      },
      {
        format: "sms_short",
        predicted_engagement: 0.06,
        confidence: 0.7,
        reasoning: "Reaches keypad users; concise actionable message",
      },
    ],
    best_day_of_week: "Saturday",
    best_time_window: "10:00 AM–12:00 PM",
    fatigue_risk: 0.1,
    creative_suggestions: [
      "Prioritize voice/IVR in local language over digital formats",
      "Coordinate with field rep visit for in-person demonstration",
      "Low fatigue — safe to increase message frequency this week",
      "Low receptivity predicted — consider escalating to field visit or voice call",
    ],
    model_version: "campaign-receptivity-v1",
  },
};

export const CACHED_CALENDARS: Record<string, CropCalendarResponse> = {
  "Uttar Pradesh:wheat": {
    state: "Uttar Pradesh",
    crop: "wheat",
    month: "september",
    stage: "fallow",
    crop_vulnerability: 0.2,
    days_to_next: 15,
    recommendations: ["Prepare land and soil beds ahead of Rabi sowing window in October."],
    msp_rs_quintal: "2585.00",
    today_price_rs_quintal: "2469.30",
    today_arrival_metric_tonnes: "57354.99",
  },
  "Gujarat:cotton": {
    state: "Gujarat",
    crop: "cotton",
    month: "september",
    stage: "flowering",
    crop_vulnerability: 0.8,
    days_to_next: 30,
    recommendations: ["Apply 2% urea foliar spray during flowering stage."],
    msp_rs_quintal: "7710.00",
    today_price_rs_quintal: "8255.09",
    today_arrival_metric_tonnes: "1928.91",
  },
  "Bihar:rice": {
    state: "Bihar",
    crop: "rice",
    month: "september",
    stage: "flowering",
    crop_vulnerability: 0.8,
    days_to_next: 30,
    recommendations: [
      "Use stage-specific inoculants containing Azospirillum, Azotobacter, Phosphobacteria, Potash bacteria, Pseudomonas, and PPFM.",
    ],
    msp_rs_quintal: "2369.00",
    today_price_rs_quintal: "2236.51",
    today_arrival_metric_tonnes: "31940.04",
  },
  "Tamil Nadu:rice": {
    state: "Tamil Nadu",
    crop: "rice",
    month: "september",
    stage: "flowering",
    crop_vulnerability: 0.8,
    days_to_next: 30,
    recommendations: [
      "Use stage-specific inoculants containing Azospirillum, Azotobacter, Phosphobacteria, Potash bacteria, Pseudomonas, and PPFM.",
    ],
    msp_rs_quintal: "2369.00",
    today_price_rs_quintal: "2236.51",
    today_arrival_metric_tonnes: "31940.04",
  },
};
